version: "3.7"
services:
    bot:
        container_name: bot
        build:
          context: .
          dockerfile: bot.docker
        volumes:
            - ./:/app
    mongo:
        container_name: mongo
        image: mongo:3.4.20-xenial
        volumes:
            - mongo_data:/data/db
            
volumes:
  mongo_data:
          